### PR TITLE
Add a configuration file to override environment in pre-commit script.

### PR DESCRIPTION
**Pull request by miceno**
Allow configuration of a custom PHP binary.

### CODE REVIEW

**Comment by dakanji** [comment]
Hi,

Can you explain what this does and why it is needed?

Also, where is .hook-config?

**Comment by miceno** [comment]
It `sources` a configuration script with variables that will override the hook environment, so I can select another  `php` binary for my environment.

File `.hook-config` is a `bash` script containing variables that will override the default environment. I didn't include it in the repo to avoid committing it by mistake in case I have one in my environment.

**Comment by dakanji** [comment]
Hi,

Still not clear what exactly this does and why it is needed in the project. Seems to be something very specific to you (not all parts needed for it to work are in the PR for instance).

**Comment by miceno** [comment]
The reason I created this code is that I had to install a non-system `php` binary (the one provided by Apple didn't include `pcntl` required module). I had to install it in a different place so it was available as `php` on the standard PATH.

I think it is not specific to me, but the opposite: current implementation was too specific since some of the configuration in `pre-commit` was hardcoded. Using the `.hook-config` feature, a developer can override the defaults and use their own `php` binary for example.

The reason for not including `.hook-config` file is that it is not required, it is optional and thus, you may or not use it. But if you consider this feature is more sound with that file, I will commit it.

**Comment by dakanji** [comment]
Thanks but there is only one PHP command in the hook and this is only to check for syntax errors. 
I am struggling to see why this needs a special PHP binary or am I missing something?

**Comment by miceno** [comment]
You are right, no need to include it. Closing the PR.

**Pull request closed without merging**
