### PR TITLE
Allow ignoring local composer exec

### PR DESCRIPTION
**Pull request by miceno**

### CODE REVIEW

**Review by dakanji — COMMENTED** [review]
There should be no need for a composer.phar file in the project. I.E., composer should be installed globally on the machine

**Comment by miceno** [comment]
I will try to install it globally, but it was easier for me this way.

**Comment by dakanji** [comment]
Maybe better to just distribute the phar file

**Comment by dakanji** [comment]
On second thoughts, best to let each user decide. Will merge this

**Pull request merged**
