### PR TITLE
Solve a typo on the ruleset

### LINKED ISSUE #84: Bad result of Code Beautifier pre-commit hook
If I run the beautifier from the command line, I get this error:

```G2Project-main$ dev_vendor/bin/phpcbf --standard=$PWD/phpcs.xml $PWD/main.php 
ERROR: Ruleset G2Project-main/phpcs.xml is not valid

Run "phpcbf --help" for usage information

```

### PR DESCRIPTION
**Pull request by miceno**
Closes #84

### CODE REVIEW

**Comment by dakanji** [comment]
This one is strange as the "<" operator is a valid one: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/wiki/Customizable-sniff-properties#array-alignment-dealing-with-multi-line-items

Also works fine on my machine as is ... so not so sure about the change.

**Review by dakanji — COMMENTED** [review]
Not so sure about the change from < ? xml version="1.0" ? >. Again, this works for me and is theformat in the official repo for phpcs: https://github.com/squizlabs/PHP_CodeSniffer/blob/master/phpcs.xml.dist

Are you sure there is nothing in your setup driving these issues?

**Comment by miceno** [comment]
I will try it again, since I had run "composer update" and that might be the problem... I will check it again.

**Comment by dakanji** [comment]
i have updated. That rule can be dealt with elsewhere.

**Pull request merged**
