### PR TITLE
Update graphic toolkits to allow the latest version of commands

### LINKED ISSUE #73: Support for new versions of graphic toolkits
When activating imagemagick module when using version 6.8 or greater, the following message appears after running the test on the plugin configuration page:

```

Failed
Error messages: 
Binary output:
/homepages/9/d230229885/htdocs/g2php7.estotienearreglo.es/modules/imagemagick/data/test.gif GIF 50x50 50x50+0+0 8-bit sRGB 8c 232B 0.000u 0:00.000
```

The issue is related to the way the new version of ImageMagick reports the type of file.

On file `ImageMagickToolkitHelper.class` shows the issue is related to the regular expression:

https://github.com/dakanji/G2Project-main/blob/cb5b7eee1a918ca33ad141f81c3b8d07491924e0/modules/imagemagick/classes/ImageMagickToolkitHelper.class#L252 

Jpegtran module is also outdated, since Jpegtran current version 9 produces a different text that is not compatible with current code.

GD is also updated, see following result on my hosting:

GD version | Required | Pass/fail
--------- | ------- | -------
2.1.0 (bundled) | 2.0 | Failed! This GD version is too old and is not supported by this module! Please upgrade your PHP installation to include the latest GD version.

### PR DESCRIPTION
**Pull request by miceno**
Update to support available app versions for each toolkit:
* jpegtran > 9a
* GD > 2.1
* ImageMagick > 6.8.9

Closes #73

### CODE REVIEW

**Comment by dakanji** [comment]
So this has crashed and burnt. That's why I asked to wait a little while and work from what was going to be pushed out. Sorry.

The track that will be taken is to

1. Sort out a Gallery 2 "Minimal" file set
2. Expand this to a  Gallery 2 "Typical" file set
3. Take on other modules
4. Look into other stuff

jpegtran is not in the minimal file set but you can push to the [G2Project-modules Repo](https://github.com/dakanji/G2Project-modules) in the meantime if you want.

Idea is to have a structured step wise process with options to add to G2Project-modules and/or G2Project-themes in the interim if desired.

What will be great would be taking on #77 if possible.

Thanks

**Comment by miceno** [comment]
I am afraid you broke something when merging this... I suggest you undo all the branch merge and I will try to create a separate branch for each of the toolkits, it will be cleaner than this. right now it is a bit of a mess :(

**Comment by miceno** [comment]
I think it will be better if I take it from here and I will try to solve it. I will create a separate branch for each of the toolkit, there is no need for you to undo the changes, i will take of them.
I will do it tomorrow, too late for today in Spain ;)

**Comment by dakanji** [comment]
Rolled back the changes

**Comment by miceno** [comment]
Hi, You have alreaady merge the solution to this in #88 , so no need to rollback :)

**Comment by miceno** [comment]
I am afraid you have broken it again :(

**Comment by dakanji** [comment]
> I am afraid you broke something when merging this... I suggest you undo all the branch merge and I will try to create a separate branch for each of the toolkits, it will be cleaner than this. right now it is a bit of a mess :(

I just followed this!

**Comment by miceno** [comment]
I prefer we all work on a branch first, test it and then merge onto dev. As of now, working directly on the dev branch, we have broken code in it :(

**Comment by miceno** [comment]
> > I am afraid you broke something when merging this... I suggest you undo all the branch merge and I will try to create a separate branch for each of the toolkits, it will be cleaner than this. right now it is a bit of a mess :(
> 
> I just followed this!

But there was another message that I will take from here and I will solve it in a separate PR (it was #88 , so I thought you got my second message. I think we need another communication means, it is not working very well through github.

**Comment by dakanji** [comment]
Sorry about my confusion but there is no reason why Github can't work.  All we need to do is make sure we cross reference items.

So for instance, if you added a note to say "This is a separate PR to resolve issues in #xyz" then when I am catching up on your stuff, I will know what your intention is.

I couldn't tell the two items were linked.

I will do the same on my side.

**Comment by miceno** [comment]
I agree! Let's try it this way :)

**Comment by dakanji** [comment]
Cool. I will now restore things back to where they where before my reset

**Comment by miceno** [comment]
Thank you!

**Pull request merged**
