### PR TITLE
Broken translations scripts

### LINKED ISSUE #90: Broken scripts for translations
I was following the procedure described in Gallery2 Codex to translate a module.

While running `make es.po` to get the PO file, I got the following error:
```
../../../lib/tools/po/GNUmakefile.inc:27: *** missing separator.  Stop.
```

It looks like PHP CS Fixer changed the layout of the file.

In order to solve it I have used the original `/lib/tools/po/GNUmakefile.inc` files, and it works without a problem.

Then the problem comes on the `extract.php` file, that has also changed from the original one. I tried it with PHP 7 and PHP 5, and for both it rises an error.

So I finally came up with the original `/lib/tools/po` folder and it works like a charm. 

I will prepare a PR on this.

### PR DESCRIPTION
**Pull request by miceno**
Use original code from v2.3.2
Closes #90

### CODE REVIEW

**Comment by miceno** [comment]
Please, do not merge... again the CS fixer changed the `GNUMakefile.inc` file. I will disable the pre-commit hook to commit it again.

**Comment by dakanji** [comment]
Not too keen to roll back to the original code here due to use of `eval` which `$gallery->runEval` replaces. Solution should focus on the `GNUMakefile.inc` file.

Will update hook to exclude these

**Comment by miceno** [comment]
To be honest, don't know the way to make it work using `$gallery`, so I suggest to keep the old code till we find a better way to do it. I suggest to  open an issue so we will have it in mind for the future.

**Comment by dakanji** [comment]
I.E., these have c/c++ code and hook assumes *.inc files are php.

I think I know the solution for the specific error in https://github.com/dakanji/G2Project-main/issues/90. Will push this later and you can test.

**Comment by miceno** [comment]
Great! I will keep the PR closed till you advice 👍

**Comment by dakanji** [comment]
Hi.

Can you fetch the `stream/translation-fix ` branch and test?
If this fails, will be interested to know if GNUMakefile.inc fails or extract.php or both.

**Comment by miceno** [comment]
Give me some minutes and I will notify you through here...

**Comment by dakanji** [comment]
Thanks. If GNUMakefile.inc fails, swap in the original version and test if extract.php still fails.

**Comment by miceno** [comment]
Tried both things, but none solved it.

`GNUMakefile.inc` was badly formatted: the line with `G2DATA = $( shell ` should be in just one line, if you try to break it up, it will not work. In addition, I updated single and double quotes. See it at https://github.com/miceno/G2Project-main/tree/stream/translation-fix

Concerning the `extract.php` file, the point is that `$gallery` object is usually initialized globally by the `main.php` script, and we don't have it available here. As these scripts are prepared to run isolated from the Gallery code, I think we should consider a different strategy.

**Comment by miceno** [comment]
I am reviewing the implementation of `runEval` and I think you can duplicate it. Or is it you were trying to avoid repeating code?

**Comment by miceno** [comment]
um ... just realized about a problem with the beautifier pre-commit script... I have partially committed the changes I made to `GNUMakefile.inc` file (I didn't include in the commit the change on the path to PHP), but when the commit script run, it commited all the changes on `GNUMakefile`. I will report it as an issue on the main repo.

**Comment by dakanji** [comment]
> Tried both things, but none solved it.
> 
> `GNUMakefile.inc` was badly formatted: the line with `G2DATA = $( shell ` should be in just one line, if you try to break it up, it will not work. In addition, I updated single and double quotes. See it at https://github.com/miceno/G2Project-main/tree/stream/translation-fix
> 
> Concerning the `extract.php` file, the point is that `$gallery` object is usually initialized globally by the `main.php` script, and we don't have it available here. As these scripts are prepared to run isolated from the Gallery code, I think we should consider a different strategy.

Thanks for the feedback. Will make a few adjustments accordingly.

**Comment by dakanji** [comment]
> I am reviewing the implementation of `runEval` and I think you can duplicate it. Or is it you were trying to avoid repeating code?

Hold off for now so we don't step on each other's toes on this.

**Comment by dakanji** [comment]
> um ... just realized about a problem with the beautifier pre-commit script... I have partially committed the changes I made to `GNUMakefile.inc` file (I didn't include in the commit the change on the path to PHP), but when the commit script run, it commited all the changes on `GNUMakefile`. I will report it as an issue on the main repo.

Don't understand but do raise the issue and I will try to understand in there.

**Comment by dakanji** [comment]
Can you pull the branch and have another go?

**Comment by miceno** [comment]
Better, much more better,... right now there are no big errors, just this:
```bash

orestes$ make ca.po
strings.raw:4: atenci'on: msgid vac'io. Est'a reservado por el gettext de GNU:
                          gettext("") regresa la l'inea de encabezado con la
                          metainformaci'on, no una cadena vac'ia.
```
It is is Spanish, I don't know why :( All my config is in English.

This is the content of `strings.raw`:
```
# $Id$

/* module.inc */
gettext("")

/* templates/Admin.tpl */
gettext("Links In The Head - Settings")
gettext("Settings saved successfully")
gettext("Enter the links you would like displayed in the header. Any URL left empty will not be used.")
gettext("Links")
gettext("Link Name:")
gettext("URL:")
gettext("Save")
```

With the code from original version 2.3.2 I got this:
```
# $Id$

/* module.inc */
gettext("Links In The Head")
gettext("Add links to the header menu.")
gettext("Extra Data")

/* templates/Admin.tpl */
gettext("Links In The Head - Settings")
gettext("Settings saved successfully")
gettext("Enter the links you would like displayed in the header. Any URL left empty will not be used.")
gettext("Links")
gettext("Link Name:")
gettext("URL:")
gettext("Save")
```

Some strings don't appear on the translation file, those on `module.inc` for instance. I am try to review it, but I can't find it yet... The strings that do not appear are the ones that are enclosed in `i18n`, see here:

```php

 public function __construct()
	{
		global $gallery;

		$this->setId('linksinthehead');
		$this->setName($gallery->i18n('Links In The Head'));
		$this->setDescription($gallery->i18n('Add links to the header menu.'));
		$this->setVersion('0.1.2');
		$this->setGroup('data', $gallery->i18n('Extra Data'));
		$this->setCallbacks('getSystemLinks|getSiteAdminViews');
		$this->setRequiredCoreApi(array(7, 10));
		$this->setRequiredModuleApi(array(3, 0));
	}
```

**Comment by miceno** [comment]
I open the PR again, so it is easier to follow it, on closed status, I have to click on the filters to show it.

**Comment by dakanji** [comment]
Let's continue in https://github.com/dakanji/G2Project-main/issues/90 instead

**Pull request closed without merging**
